name: Build plugin

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10

env:
  PLUGIN_NAME: logseq-open-in-windsurf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x" # You might need to adjust this value to your own version
      - name: Build
        id: build
        run: |
          npm install -g yarn
          yarn
          yarn build
          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md package.json icon.png demo.gif ${{ env.PLUGIN_NAME }}
          mv dist ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
          echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_OUTPUT
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          files: |
            ./${{ env.PLUGIN_NAME }}.zip
            ./package.json
          name: Release ${{ steps.build.outputs.tag_name }}
          tag_name: ${{ steps.build.outputs.tag_name }}