name: Publish Logseq Plugin

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: logseq-open-in-windsurf

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build plugin
        run: yarn build

      - name: Prepare release assets
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md package.json icon.png ${{ env.PLUGIN_NAME }} || true
          if [ -f demo.gif ]; then cp demo.gif ${{ env.PLUGIN_NAME }}/; fi
          if [ -d dist ]; then mv dist ${{ env.PLUGIN_NAME }}/; fi
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            package.json
          prerelease: false
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}